name: service_client
description: An http client interface.
version: 0.1.1
repository: https://github.com/macss-dev/service_client

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  cryptography: ^2.9.0
  http: ^1.6.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
